### ISSUE TITLE
Milestone tracker not working for Fetch Dog CEO or Toy Tale labs

### ISSUE THREAD

**Issue by keilkyle** [learn-co-curriculum/phase-1-practice-toy-tale#5]
https://base.flatironschool.com/milestones

- I finished both the Fetch Dog CEO and Toy Tale labs, but they aren't updating on the milestone tracker. Am I submitting things wrong?

**Comment by lizbur10** [comment]
Hi @keilkyle! GitHub issues are monitored by the team responsible for maintaining the material in Canvas - the Milestones are handled by a different area. I do know that some upgrades were recently made to the Milestones system and that they are working out some kinks. Hopefully it will clear up soon but, if it doesn't, please reach out to your instructor/cohort lead  to get help.

Apologies for the inconvenience! 💙
