### ISSUE TITLE
Wish There Were More Hints In This Lab

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-1-practice-toy-tale#9]
### Canvas Link

https://learning.flatironschool.com/courses/5284/assignments/172018?module_item_id=385019

### Concern

Found this lab to be very difficult in comparison.

Wish there were a few more hints present.

**Comment by professor-ben** [comment]
Hi Samuel,

Thanks so much for letting us know. We agree that this lab is a bit difficult and will update it to add more context for the next cohort that comes through. In the meantime, the instructors and technical coaches are all very familiar with these labs and should be a great resource for that additional context.

Thank you,
Ben
